var annotated_dup =
[
    [ "uniot", "namespaceuniot.html", [
      [ "JSON", "namespaceuniot_1_1_j_s_o_n.html", [
        [ "Array", "classuniot_1_1_j_s_o_n_1_1_array.html", "classuniot_1_1_j_s_o_n_1_1_array" ],
        [ "Object", "classuniot_1_1_j_s_o_n_1_1_object.html", "classuniot_1_1_j_s_o_n_1_1_object" ]
      ] ],
      [ "AppKit", "classuniot_1_1_app_kit.html", "classuniot_1_1_app_kit" ],
      [ "Array", "classuniot_1_1_array.html", "classuniot_1_1_array" ],
      [ "Button", "classuniot_1_1_button.html", "classuniot_1_1_button" ],
      [ "CallbackEventListener", "classuniot_1_1_callback_event_listener.html", "classuniot_1_1_callback_event_listener" ],
      [ "CallbackMQTTDevice", "classuniot_1_1_callback_m_q_t_t_device.html", "classuniot_1_1_callback_m_q_t_t_device" ],
      [ "CBORObject", "classuniot_1_1_c_b_o_r_object.html", "classuniot_1_1_c_b_o_r_object" ],
      [ "CBORStorage", "classuniot_1_1_c_b_o_r_storage.html", "classuniot_1_1_c_b_o_r_storage" ],
      [ "ConfigCaptivePortal", "classuniot_1_1_config_captive_portal.html", "classuniot_1_1_config_captive_portal" ],
      [ "COSEMessage", "classuniot_1_1_c_o_s_e_message.html", "classuniot_1_1_c_o_s_e_message" ],
      [ "CrashStorage", "classuniot_1_1_crash_storage.html", "classuniot_1_1_crash_storage" ],
      [ "Credentials", "classuniot_1_1_credentials.html", "classuniot_1_1_credentials" ],
      [ "DataChannels", "classuniot_1_1_data_channels.html", "classuniot_1_1_data_channels" ],
      [ "Date", "classuniot_1_1_date.html", "classuniot_1_1_date" ],
      [ "DetailedAsyncWebServer", "classuniot_1_1_detailed_async_web_server.html", "classuniot_1_1_detailed_async_web_server" ],
      [ "ESP32Task", "classuniot_1_1_e_s_p32_task.html", "classuniot_1_1_e_s_p32_task" ],
      [ "ESP32WifiScan", "classuniot_1_1_e_s_p32_wifi_scan.html", "classuniot_1_1_e_s_p32_wifi_scan" ],
      [ "ESP8266Task", "classuniot_1_1_e_s_p8266_task.html", "classuniot_1_1_e_s_p8266_task" ],
      [ "ESP8266WifiScan", "classuniot_1_1_e_s_p8266_wifi_scan.html", "classuniot_1_1_e_s_p8266_wifi_scan" ],
      [ "EventBus", "classuniot_1_1_event_bus.html", "classuniot_1_1_event_bus" ],
      [ "EventEmitter", "classuniot_1_1_event_emitter.html", "classuniot_1_1_event_emitter" ],
      [ "EventEntity", "classuniot_1_1_event_entity.html", "classuniot_1_1_event_entity" ],
      [ "EventListener", "classuniot_1_1_event_listener.html", "classuniot_1_1_event_listener" ],
      [ "GlobalBufferMemoryManager", "classuniot_1_1_global_buffer_memory_manager.html", null ],
      [ "GpioRegister", "classuniot_1_1_gpio_register.html", "classuniot_1_1_gpio_register" ],
      [ "ICOSESigner", "classuniot_1_1_i_c_o_s_e_signer.html", "classuniot_1_1_i_c_o_s_e_signer" ],
      [ "IEventBusConnectionKit", "classuniot_1_1_i_event_bus_connection_kit.html", "classuniot_1_1_i_event_bus_connection_kit" ],
      [ "IExecutor", "classuniot_1_1_i_executor.html", "classuniot_1_1_i_executor" ],
      [ "IncomingEventManager", "classuniot_1_1_incoming_event_manager.html", "classuniot_1_1_incoming_event_manager" ],
      [ "ISchedulerConnectionKit", "classuniot_1_1_i_scheduler_connection_kit.html", "classuniot_1_1_i_scheduler_connection_kit" ],
      [ "IWithType", "classuniot_1_1_i_with_type.html", "classuniot_1_1_i_with_type" ],
      [ "Lisp", "classuniot_1_1_lisp.html", "classuniot_1_1_lisp" ],
      [ "LispDevice", "classuniot_1_1_lisp_device.html", "classuniot_1_1_lisp_device" ],
      [ "LispEvent", "structuniot_1_1_lisp_event.html", "structuniot_1_1_lisp_event" ],
      [ "Map", "classuniot_1_1_map.html", "classuniot_1_1_map" ],
      [ "MQTTDevice", "classuniot_1_1_m_q_t_t_device.html", "classuniot_1_1_m_q_t_t_device" ],
      [ "MQTTKit", "classuniot_1_1_m_q_t_t_kit.html", "classuniot_1_1_m_q_t_t_kit" ],
      [ "MQTTPath", "classuniot_1_1_m_q_t_t_path.html", "classuniot_1_1_m_q_t_t_path" ],
      [ "NetworkController", "classuniot_1_1_network_controller.html", "classuniot_1_1_network_controller" ],
      [ "NetworkScheduler", "classuniot_1_1_network_scheduler.html", "classuniot_1_1_network_scheduler" ],
      [ "NVSFile", "classuniot_1_1_n_v_s_file.html", "classuniot_1_1_n_v_s_file" ],
      [ "NVSFileSystem", "classuniot_1_1_n_v_s_file_system.html", "classuniot_1_1_n_v_s_file_system" ],
      [ "ObjectRegister", "classuniot_1_1_object_register.html", "classuniot_1_1_object_register" ],
      [ "ObjectRegisterRecord", "classuniot_1_1_object_register_record.html", "classuniot_1_1_object_register_record" ],
      [ "PrimitiveExpeditor", "classuniot_1_1_primitive_expeditor.html", "classuniot_1_1_primitive_expeditor" ],
      [ "Register", "classuniot_1_1_register.html", "classuniot_1_1_register" ],
      [ "RegisterManager", "classuniot_1_1_register_manager.html", "classuniot_1_1_register_manager" ],
      [ "RegisterManagerProxy", "classuniot_1_1_register_manager_proxy.html", "classuniot_1_1_register_manager_proxy" ],
      [ "SchedulerTask", "classuniot_1_1_scheduler_task.html", "classuniot_1_1_scheduler_task" ],
      [ "SimpleNTP", "classuniot_1_1_simple_n_t_p.html", "classuniot_1_1_simple_n_t_p" ],
      [ "Singleton", "classuniot_1_1_singleton.html", "classuniot_1_1_singleton" ],
      [ "Storage", "classuniot_1_1_storage.html", "classuniot_1_1_storage" ],
      [ "TaskScheduler", "classuniot_1_1_task_scheduler.html", "classuniot_1_1_task_scheduler" ],
      [ "TopDevice", "classuniot_1_1_top_device.html", "classuniot_1_1_top_device" ],
      [ "Type", "classuniot_1_1_type.html", null ],
      [ "unLisp", "classuniot_1_1un_lisp.html", "classuniot_1_1un_lisp" ],
      [ "WifiStorage", "classuniot_1_1_wifi_storage.html", "classuniot_1_1_wifi_storage" ]
    ] ],
    [ "Bytes", "class_bytes.html", "class_bytes" ],
    [ "ClearQueue", "class_clear_queue.html", "class_clear_queue" ],
    [ "FourCC", "struct_four_c_c.html", null ],
    [ "IterableQueue", "class_iterable_queue.html", "class_iterable_queue" ],
    [ "LimitedQueue", "class_limited_queue.html", "class_limited_queue" ],
    [ "UniotCore", "class_uniot_core.html", "class_uniot_core" ]
];